version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/app
      - public:/app/public # 追加
      - tmp:/app/tmp # 追加
    # ports:
    #   - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx: # 追加
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # ここ
      - public:/app/public # 追加
      - tmp:/app/tmp # 追加
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql-data:
    driver: local
  tmp: # 追加
  public: # 追加
