// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import QuizFormController from "./quiz_form_controller"
application.register("quiz-form", QuizFormController)

import QuizFormForShowController from "./quiz_form_for_show_controller"
application.register("quiz-form-for-show", QuizFormForShowController)
